version: '2'
services:
  web:
    image: ruby
    working_dir: /usr/local/src
    volumes:
      - .:/usr/local/src
      - bundle:/usr/local/bundle
    environment:
      - RACK_ENV=test

volumes:
  bundle: {}
